### ISSUE TITLE
A small inaccuracy in your blogpost

### ISSUE THREAD

**Issue by kha84** [COMP0016-Team-24/COMP0016-Team-24.github.io#1]
Hello guys,

I know it has been few years since you were working on that your [Lab Virtual Assistant Lab Project](https://students.cs.ucl.ac.uk/2020/group24/index.html). But I had to dive myself into this topic of Linux audio and google found this your blogpost - [Passing audio into docker container](https://comp0016-team-24.github.io/dev/problem-solving/2020/10/30/passing-audio-into-docker.html)
I wanted to highlight, that there's one inaccurate piece of information there. You say:

>and ALSA itself does not provide audio mixing capabilities which allows multiple apps to play or record at the same time

Actually it does. There's such a thing as **dmix**. And a sound server even can be configured to use it, so you can have both native ALSA clients and Pipewire clients using the same device at the same time:

* https://wiki.archlinux.org/title/Advanced_Linux_Sound_Architecture#Dmix
* https://wiki.archlinux.org/title/PipeWire#Use_ALSA_dmix_devices_as_PipeWire_sinks

**Comment by micromaomao** [comment]
Hi @kha84 

Thanks for spotting this and submitting an issue! I will update the post to point out the extra info you provided (unless you prefer to contribute a PR which I would also be happy to review).

I'm a bit afraid that I'm not exactly knowledgeable on the Linux audio ecosystem - from what you linked it sounds like passing through the ALSA audio device could actually work fine, but this would require both your desktop audio server _and_ the container to use dmix, and (at least in some cases) this needs some extra config. Whereas passing through the pulseaudio socket / other Pipewire mechanism would always work... And therefore the general idea in the article still holds true, that (unless you have some specific dmix setup) you should not pass through the audio device to the container...?

Please let me know if I'm understanding this correctly.

**Comment by kha84** [comment]
Hello @micromaomao

Yes, your understanding is exactly matching to my own understanding :) 
In order to use the same ALSA device via sound server (Pipewire/Pulseaudio) on your host and as pure ALSA device in a container, the sound server must also be reconfigured - so they both will be using dmix. I.e. the overall setup will be something like this:

![Docker-audio-via-Alsa drawio](https://user-images.githubusercontent.com/110789576/226130019-0dc0434d-2304-4119-ad14-7a50e6cbf9e1.png)

Sure, this little correction doesn't cancel the whole idea of your article, and forgive me my manners, I forgot to thank you for it - it helped me a lot to advance myself towards what I'm doing.

And btw, the Pipewire (which is becoming a standard nowdays) can happily emulate the Pulseaudio socket file descriptor, and I managed to use in in the pretty similar configuration, as you were describing on your article. So thanks again for that. 

This is my final setup:

![Docker-audio-via-Pipewire-emulation-of-Pulseaudio drawio](https://user-images.githubusercontent.com/110789576/226136017-c55fe043-fb04-42da-97f8-22decb53e565.png)

And here is how to use that in Docker:

## Alpine container

```
docker run \
  -v /run/user/1000/pulse/native:/run/user/1000/pulse/native \
  -e PULSE_SERVER=unix:/run/user/1000/pulse/native \
  -it --rm alpine /bin/ash

# install ALSA->pulseaudio bridge, native pulseaudio clients like "parec" and "pacat" 
apk add alsa-plugins-pulse pulseaudio-utils

# test that playback via native PulseAudio tools is working fine
parec test.wav
pacat test.wav

# check how the our Pipewire server on a host is looking like, from this container
pactl info
paclt list

# install alsa-utils
apk add alsa-utils

# test if everything works from ALSA perspective
aplay -L
speaker-test -c2
```

## Fedora container

```
docker run \
  -v /run/user/1000/pulse/native:/run/user/1000/pulse/native \
  -e PULSE_SERVER=unix:/run/user/1000/pulse/native \
  -it --rm fedora /bin/sh

# make sure the native pulseaudio client work
yum install pulseaudio-utils.x86_64 

parec test.wav
pacat test.wav

# install ALSA utilities (aplay, arecord) and ALSA virtual device "pulseaudio" 
# the funny thing here, that alsa-plugins-pulseaudio is actually bringing the Pipewire :)
yum install alsa-utils alsa-plugins-pulseaudio.x86_64

# test if everything works
aplay -L
speaker-test -Dpulse -c2
arecord -d 5 -Dpulse test.wav
aplay -Dpulse test.wav
```

**Comment by micromaomao** [comment]
Page [updated](https://comp0016-team-24.github.io/dev/problem-solving/2020/10/30/passing-audio-into-docker.html).

Thanks again for reporting!
